export const CONSTANTS = {
  DEBIT_CARD_HEADER_TITLE: 'Debit Card',
  SET_LIMIT_HEADER_TITLE: 'Spending limit',
  SET_LIMIT_SUBTITLE: 'Here weekly means the last 7 days - not the calendar week',
  DEBIT_CARD_SPENDING_LIMIT: 'Debit card spending limit',
  AVAILABLE_BALANCE: 'Available balance',
  CURRENCY_SYMBOL: 'S$',
  SHOW_CARD_NUMBER: 'Show card number',
  HIDE_CARD_NUMBER: 'Hide card number',
  HIDDEN_CARD_DOTS: '●●●●●●●●●●●●',
  CVV_PREFIX: 'CVV: ',
  EXP_DATE_PREFIX: 'Thru: ',
  LOADING: 'Loading...',
  SORRY_ERROR: 'Sorry, connection with server failed.',
  SET_LIMIT_MESSAGE: 'Set a weekly debit card spending limit',
  OPTION_TITLE_DEBIT_TOP_UP: 'Top-up account',
  OPTION_SUBTITLE_TOP_UP: 'Deposit money to your account to use with card',
  OPTION_TITLE_WEEKLY_SPENDING: 'Weekly spending limit',
  OPTION_SUBTITLE_WEEKLY_SPENDING: "You havn't set any spending limit on card",
  OPTION_SUBTITLE_WEEKLY_SPENDING_ENABLE: 'Your weekly spending limit is S$ ',
  OPTION_TITLE_FREEZE_CARD: 'Freeze card',
  OPTION_SUBTITLE_FREEZE_CARD: 'Your debit card is currently active',
  OPTION_TITLE_GET_NEW_CARD: 'Get a new card',
  OPTION_SUBTITLE_GET_NEW_CARD: 'This deactivates your current debit card',
  OPTION_TITLE_DEACTIVATED_CARD: 'Deactivated cards',
  OPTION_SUBTITLE_DEACTIVATED_CARDS: 'Your previously deactivated cards',
  SAVE: 'Save',
  QUICK_BUTTON_5: 'S$ 5,000',
  QUICK_BUTTON_10: 'S$ 10,000',
  QUICK_BUTTON_20: 'S$ 20,000',
};
