export const IMAGE_ASSETS = {
    HOME_ACTIVE: require('../../../assets/home_active.png'),
    HOME_INACTIVE: require('../../../assets/home_inactive.png'),
    DEBIT_ACTIVE: require('../../../assets/debit_active.png'),
    DEBIT_INACTIVE: require('../../../assets/debit_inactive.png'),
    PAYMENTS_ACTIVE: require('../../../assets/payments_active.png'),
    PAYMENTS_INACTIVE: require('../../../assets/payments_inactive.png'),
    CREDIT_ACTIVE: require('../../../assets/credit_active.png'),
    CREDIT_INACTIVE: require('../../../assets/credit_inactive.png'),
    PROFILE_ACTIVE: require('../../../assets/profile_active.png'),
    PROFILE_INACTIVE: require('../../../assets/profile_inactive.png'),
    APP_LOGO: require('../../../assets/app_logo.png'),
    APP_LOGO_WHITE: require('../../../assets/app_logo_white.png'),
    ICON_TOP_UP: require('../../../assets/icon_top_up.png'),
    ICON_DEACTIVATED_CARDS: require('../../../assets/icon_deactivated_cards.png'),
    ICON_LIMIT_DARK: require('../../../assets/icon_limit_dark.png'),
    ICON_LIMIT_LIGHT: require('../../../assets/icon_limit_light.png'),
    ICON_FREEZE: require('../../../assets/icon_freeze_card.png'),
    ICON_ADD_CARD: require('../../../assets/icon_add_card.png'),
    ICON_VISA_WHITE: require('../../../assets/icon_visa_white.png'),
    ICON_RED_EYE_CLOSE: require('../../../assets/icon_red_eye_close.png'),
    ICON_RED_EYE_OPEN: require('../../../assets/icon_red_eye_open.png'),
    ICON_CARD_BRAND: require('../../../assets/icon_card_brand.png'),
    ICON_BACK: require('../../../assets/icon_back.png'),
}